import type { Metadata } from "next";
import { DM_Serif_Display, Jost } from "next/font/google";

import "./globals.css";

const dm_serif_display = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm_serif_display",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_serif_display.variable} ${jost.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
